### ISSUE TITLE
Offer option to make the app always open Jupyter

### ISSUE THREAD

**Issue by slel** [3-manifolds/Sage_macOS#14]
Currently, each time the app is launched, it lets the user choose
whether to open the Sage REPL or the Jupyter Notebook.

It would be nice to offer an option to make that choice stick,
so that the next times the app is launched, the same way of
using Sage is selected (whether it is the REPL or Jupyter).

Requested at

- [Ask Sage question 57666](https://ask.sagemath.org/question/57666)

**Comment by culler** [comment]
That is not exactly what was requested in the linked post, but is a much better suggestion.

You are requesting a preferences setting which would determine which interface is the default.  The value of this would be that it could save the user one mouse click when starting sage.  The cost of this is that it would require adding preferences to the app.  Currently the app does not have any preferences settings.  The reason for that choice was that there did not seem to be any preferences settings which would be sufficiently valuable to warrant the increased complexity of the app which would result if preferences were added.

I do not want to do this for the 9.3 app.  I am willing to consider it for the 9.4 app.  Perhaps some preferences settings will emege which would would justify the added complexity.  Given that the average user clicks their mouse about 1000 times per day, it is not clear to me that eliminating one mouse click per sage launch is worth it.  But I will keep an open mind.

I do not support the suggestion in the linked post, that the choice of interface should only be available when the user control-clicks the app icon.  I do not believe the claim that "most" apps behave that way and do not want to require that our users know an obscure secret handshake in order to have a choice of which interface to use with sage.

**Comment by NathanDunfield** [comment]
I agree with Marc that perhaps this convenience is not worth the extra complexity.  I guess the easiest way to do it, which still requires a config file saved somewhere, is to have it default to whatever was selected the previous time the app was used.  But perhaps other users would find that behavior annoying...

**Comment by culler** [comment]
Indeed, saving the state of the window and restoring that state on the next
launch would be easy to do.  The only hitch that I see is that if the user
uninstalled iTerm between the two launchings then it might not be possible
to restore the state.  Still, that does not require much logic to work
around.

Nonetheless, I would prefer to add a feature like that to the next
release.  I am treating the 9.3 release as frozen, except for bug fixes.

**Comment by culler** [comment]
The Sage 9.4 version of the app will make the state of the launcher window persist across restarting the app.  The app was already remembering the user's choice of notebook directory in a plain text file.  That information has been moved into a config file which also remembers whether the user last used a jupyter notebook or a cli interface, and in the latter case it remembers which terminal application was used.

I think that means that this ticket can be closed.
