### ISSUE TITLE
SageMath-9.3.dmg:  SIGILL on MBP13 M1 macOS 11.5.1

### ISSUE THREAD

**Issue by GMS103** [3-manifolds/Sage_macOS#23]
On the other hand, SageMath-9.2.dmg works fine.

I attach the crash report.

[python3.9_2021-08-07-185153_MBP13M1.crash.txt](https://github.com/3-manifolds/Sage_macOS/files/6949476/python3.9_2021-08-07-185153_MBP13M1.crash.txt)

**Comment by NathanDunfield** [comment]
Please try the [prerelease version of 9.4](https://github.com/3-manifolds/Sage_macOS/releases/tag/v1.2-rc.0), and let us know whether it works.  Alternatively, an option which provides *native* support for the M1 processor is to install [Sage via Conda](https://groups.google.com/g/sage-devel/c/l0Kv4InEDiI/m/9JEEJ7KyCwAJ).

**Comment by culler** [comment]
Even if you install conda, please test the 9.4 prerelease.  We really want to know if our effort succeeded, and we are not able to test this ourselves.  The 9.2 release used the official Sage binaries while the 9.3 release was compiled on a Big Sur system with a relatively new processor.  So we expect a difference.  The 9.4 prerelease was compiled in the same Big Sur system, but with many modifications to the build process aiming at preventing the compiler from using instructions that are not recognized on older CPUs.  These same instructions are likely to cause trouble with Apple's emulator.  We want to know if we have found enough of them so that the emulator will accept the code.

**Comment by GMS103** [comment]
Yes, _SageMath-9.4 Release Candidate (for Intel CPUs)_ seems to work, but I have not had the occasion to test it yet.

I shall try to keep you posted.

I prefer to wait for final versions (of SageMath, I mean) in order to install them on other people's computers.

BTW, are you planning on "universal" binaries?  It would be very nice, besides supporting older Macs (which is wonderful).

**Comment by culler** [comment]
Thank you!  That sounds very encouraging so far.

I don't know if we will make universal binaries, since 814 MB is already quite a large download.  It seems inconvenient to wait extra time and consume extra disk space because the binary files have become twice as large in order to allow them to run on someone else's computer.  I think it is more likely that we will release separate disk images for the Intel and Arm architectures.  But in any case we need to first have access to an M1 system for building and testing.

**Comment by GMS103** [comment]
Of course you are right.  Separate binaries will be much better.

**Comment by culler** [comment]
Closing this ticket since the latest release appears to run on the Intel emulator.  Once we have access to M1 hardware we will build a separate disk image targeting ARM cpus.
