### ISSUE TITLE
Where is sagetex?

### ISSUE THREAD

**Issue by Garald1** [3-manifolds/Sage_macOS#26]
Hi,

I've just installed SageMath-9.4 using the binaries given here. Where is SageTeX? I can't find sagetex.sty. For that matter, where is SAGE_ROOT?

**Comment by NathanDunfield** [comment]
Effectively, `SAGE_ROOT` is `/var/tmp/sage-9.4-current/local`.  The location of SageTeX relative to this is [described here](https://doc.sagemath.org/html/en/tutorial/sagetex.html).

**Comment by culler** [comment]
WARNING: the current binary release accidentally used the sage_conf.py file from Sage 9.3 instead of 9.4.  This may cause trouble with sagetex.  A workaround is to edit that file, replacing all occurrences of "9.3" by "9.4".  See issue #25.  The disk image in the release will be replaced with a fixed one as soon as possible (~ 2 weeks).
