### ISSUE TITLE
No module named 'sage.misc'

### ISSUE THREAD

**Issue by Nixiabing** [3-manifolds/Sage_macOS#29]
sage 9.4
macos 11.6
![image](https://user-images.githubusercontent.com/20591728/137604985-a3fc7f89-d2ac-4b13-b6c6-e5ac34cb2d7d.png)

**Comment by culler** [comment]
You don't say what you did to produce this traceback and I am not able to reproduce it on my macOS 11.6 system with a fresh install of the v1.2.1 release.  Sorry.

**Comment by Nixiabing** [comment]
emmm..when start up, it happened...
![image](https://user-images.githubusercontent.com/20591728/137609553-99abc055-9200-4147-ac66-7f2d539870f9.png)

**Comment by culler** [comment]
Since thousands of other people are using this app without anyone else having reporting this problem, and since I cannot reproduce it myself, I can only assume that your system has some very unusual configuration that somehow confuses the app.  I am not able to guess what that might be.

I suggest that you download a new copy of the v1.2.1 disk image;  move the old application to the trash (do not simply delete the app bundle, move it to the trash).  Delete or move your `~/.sage` directory, e.g. by running the command `rm -rf ~/.sage` or `mv ~/.sage ~/DOTsage`.  Remove the directory `~/Library/Application Support/SageMath`.  Then reinstall the app.  If you still see the problem, please indicate which release you downloaded, whether you installed the extra package, and any other information about your particular system that could possibly make it different from the thousands of other systems which do not have this problem.  Especially relevant would be whether you have any other installations of SageMath on the system and what they are.

You could also try running the app and selecting the Jupyter notebook instead of the terminal.  Perhaps that would give some information that would help diagnose this problem.  Unfortunately it is not possible to diagnose the problem with no information.

**Comment by culler** [comment]
One other thing. Please run the command 

`ls /Applications/SageMath-9-4.app/Contents/Frameworks/Sage.framework/Versions/9.4/local/lib/python3.9/site-packages/sage/misc`

to verify that the sage.misc module is, in fact, present in the app.  Then please check your .profile and .bashrc files to see whether you might have set up some environment variables related to either python or sage which might be causing the SageMath python to look in the wrong place for its modules.

**Comment by culler** [comment]
Another thing you could try: login as the guest user and run the SageMath app.
