### ISSUE TITLE
Extra packages wishlist

### ISSUE THREAD

**Issue by slel** [3-manifolds/Sage_macOS#34]
This issue is devoted to requests for extra packages
(as found in various discussion channels for instance).

Included in SageMath-9.4 with optional packages
(see [releases](https://github.com/3-manifolds/Sage_macOS/releases)):

- [x] 4ti2
- [x] benzene
- [x] biopython
- [x] bliss
- [x] buckygen
- [x] cbc
- [x] coxeter3
- [x] cryptominisat
- [x] csdp
- [x] e_antic
- [x] frobby
- [x] gap_packages
- [x] glucose
- [x] gp2c
- [x] igraph
- [x] ipympl
- [x] isl
- [x] kenzo
- [x] latte_int
- [x] libnauty
- [x] libsemigroups
- [x] lrslib
- [x] mcqd
- [x] meataxe
- [x] mpfrcx
- [x] normaliz
- [x] p_group_cohomology
- [x] pari_elldata
- [x] pari_galpol
- [x] pari_nftables
- [x] plantri
- [x] primecount
- [x] pycosat
- [x] pynormaliz
- [x] pysingular
- [x] qhull
- [x] saclib
- [x] sage_numerical_backends_coin
- [x] sirocco
- [x] symengine
- [x] symengine_py
- [x] tdlib
- [x] tides
- [x] topcom

Other requests:

- [ ] dot2tex -- see [Ask Sage question 60815](https://ask.sagemath.org/question/60815)

**Comment by culler** [comment]
The dot2tex package is can be installed with pip.  To make it available to the macOS app, run
`%pip install dot2tex`
It will be installed in the user's `.sage` directory.

While the app does not support `sage -i` it does support installing pypi packages and our policy is that we do not include sage optional packages that can be installed with pip.

**Comment by slel** [comment]
Would it make sense for the error message to suggest that too?

Currently:
```
$ sage -i dot2tex
Sorry, this binary distribution does not support installing sage packages.
```

Proposed:
```
$ sage -i dot2tex
Sorry, this binary distribution does not support installing extra packages with `sage -i`.
If dot2tex is pip-installable, use the following from within Sage: `%pip install dot2tex`.
```

**Comment by culler** [comment]
Sure.  I'll reopen the ticket to remind me to make that change.

**Comment by sudeepan** [comment]
For some reason, I am not being able to obtain many of these packages on version 9.5. Only kbmag seems to work.

I am using the arm64 dmg on an M1-Pro Mac.

`(base) > ~ % sage 
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.5, Release Date: 2022-01-30                     │
│ Using Python 3.9.9. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: libgap.LoadPackage("PackageManager")                                      
true
sage: libgap.InstallPackage("topcom")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmcCLlF1/exec-log.txt
#I  Package "topcom" not found in package list
false
sage: libgap.InstallPackage("pynormaliz")                                       
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmQZS3On/exec-log.txt
#I  Package "pynormaliz" not found in package list
false
sage: libgap.InstallPackage("kenzo")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmqTa5Zk/exec-log.txt
#I  Package "kenzo" not found in package list
false
sage: libgap.InstallPackage("4ti2")                                             
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmzc0RsZ/exec-log.txt
#I  Package "4ti2" not found in package list
false
sage: libgap.InstallPackage("gap_packages")                                     
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmZBeDqZ/exec-log.txt
#I  Package "gap_packages" not found in package list
false
sage: libgap.InstallPackage("frobby")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tml4Lrdn/exec-log.txt
#I  Package "frobby" not found in package list
false
sage: libgap.InstallPackage("normaliz")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmkeSLx2/exec-log.txt
#I  Package "normaliz" not found in package list
false
sage: libgap.InstallPackage("qhull")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmy3NqxW/exec-log.txt
#I  Package "qhull" not found in package list
false
sage: libgap.InstallPackage("symengine")                                        
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmNvL0L0/exec-log.txt
#I  Package "symengine" not found in package list
false
sage: libgap.InstallPackage("saclib")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmr7ml2F/exec-log.txt
#I  Package "saclib" not found in package list
false
sage: libgap.InstallPackage("kbmag")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmU2kKYO/exec-log.txt
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/kbmag/PackageInfo.g ...
#I  Possible error detected: see log at /tmp/tm17YHZt/exec-log.txt
#I  The newest version of package "kbmag" is already installed
true
sage: libgap.InstallPackage("libnauty")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmRgQbxn/exec-log.txt
#I  Package "libnauty" not found in package list
false
sage: libgap.InstallPackage("libnauty")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmDhlIGG/exec-log.txt
#I  Package "libnauty" not found in package list
false
sage: libgap.InstallPackage("glucose")                                          
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmnNVMma/exec-log.txt
#I  Package "glucose" not found in package list
false
sage:`

**Comment by sudeepan** [comment]
A lot of these packages failed for version 9.5. Only `kbmag` seems to work.

I'm using the arm64 dmg on M1-Pro Mac.

> (base) > ~ % sage 
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.5, Release Date: 2022-01-30                     │
│ Using Python 3.9.9. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: libgap.LoadPackage("PackageManager")                                      
true
sage: libgap.InstallPackage("topcom")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmcCLlF1/exec-log.txt
#I  Package "topcom" not found in package list
false
sage: libgap.InstallPackage("pynormaliz")                                       
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmQZS3On/exec-log.txt
#I  Package "pynormaliz" not found in package list
false
sage: libgap.InstallPackage("kenzo")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmqTa5Zk/exec-log.txt
#I  Package "kenzo" not found in package list
false
sage: libgap.InstallPackage("4ti2")                                             
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmzc0RsZ/exec-log.txt
#I  Package "4ti2" not found in package list
false
sage: libgap.InstallPackage("gap_packages")                                     
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmZBeDqZ/exec-log.txt
#I  Package "gap_packages" not found in package list
false
sage: libgap.InstallPackage("frobby")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tml4Lrdn/exec-log.txt
#I  Package "frobby" not found in package list
false
sage: libgap.InstallPackage("normaliz")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmkeSLx2/exec-log.txt
#I  Package "normaliz" not found in package list
false
sage: libgap.InstallPackage("qhull")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmy3NqxW/exec-log.txt
#I  Package "qhull" not found in package list
false
sage: libgap.InstallPackage("symengine")                                        
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmNvL0L0/exec-log.txt
#I  Package "symengine" not found in package list
false
sage: libgap.InstallPackage("saclib")                                           
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmr7ml2F/exec-log.txt
#I  Package "saclib" not found in package list
false
sage: libgap.InstallPackage("kbmag")                                            
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmU2kKYO/exec-log.txt
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/kbmag/PackageInfo.g ...
#I  Possible error detected: see log at /tmp/tm17YHZt/exec-log.txt
#I  The newest version of package "kbmag" is already installed
true
sage: libgap.InstallPackage("libnauty")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmRgQbxn/exec-log.txt
#I  Package "libnauty" not found in package list
false
sage: libgap.InstallPackage("libnauty")                                         
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmDhlIGG/exec-log.txt
#I  Package "libnauty" not found in package list
false
sage: libgap.InstallPackage("glucose")                                          
#I  Getting PackageInfo URLs...
#I  Possible error detected: see log at /tmp/tmnNVMma/exec-log.txt
#I  Package "glucose" not found in package list
false
sage:                                                                           

Upon checking the file `/tmp/tmcCLlF1/exec-log.txt`, it turned out to be blank.

**Comment by slel** [comment]
@sudeepan

The command `libgap.InstallPackage` is to install GAP packages.
Most of the packages you tried to install are not GAP packages,
and the failure you observed is therefore not surprising.

Furthermore all packages listed in the first comment of this issue
are already shipped with Sage-macOS in its extended form, except
for dot2tex, which is a Python package listed on PyPI, and can
therefore be installed by running:
```python
sage: %pip install dot2tex
```

**Comment by sudeepan** [comment]
Thanks! I had been using sage (compiled from source) on linux so thought packages like topcom need to be installed manually. Checked just now that in the dmg it could be used off-the-shelf, just as you said.

**Comment by slel** [comment]
This ticket seems to be creating confusion. I opened #38 for the remaining issue.
