### ISSUE TITLE
Promote 9.5, 1.3 release to stable

### ISSUE THREAD

**Issue by dconnolly** [3-manifolds/Sage_macOS#36]
Sage 9.5 is officially released and I'm trying to update the Homebrew cask recipe to use it, it feels that 1.3 is good for stable?

https://github.com/Homebrew/homebrew-cask/pull/118683

**Comment by culler** [comment]
While the 1.3 release is 3 weeks old, it has only been 2 days since the assets were updated to use the actual SageMath 9.5  release instead of the release candidate 9.5.rc3.  I don't think it is too dangerous, since there have been over 20 downloads for each architecture with no new issues (except for this one).  But I would feel more comfortable giving it a few more days.

**Comment by dconnolly** [comment]
OK yeah, thanks!

**Comment by culler** [comment]
I have upgraded the 9.5 prerelease to a release after 75 downloads without any reported issues.
