### ISSUE TITLE
homebrew sha256 mismatch

### ISSUE THREAD

**Issue by james-k-polk** [3-manifolds/Sage_macOS#37]
When using homebrew to install sage 9.5 on an Intel-based macbook the sha256 hashes don't match. It's not a homebrew problem but I'm not sure who maintains the sage cask.

```bash
arts-MacBook-Pro:~ artvandelay$ brew upgrade sage
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 6 casks.

==> Upgrading 1 outdated package:
sage 9.4,1.2.2 -> 9.5,1.3
==> Upgrading sage
==> Downloading https://github.com/3-manifolds/Sage_macOS/releases/download/v1.3/SageMath-9.5_x86_64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/341686887/1c677118-081
######################################################################## 100.0%
==> Purging files for version 9.5,1.3 of Cask sage
Error: sage: SHA256 mismatch
Expected: 21606aa7476b70a01de6594e37d74625436ac6307ccafe19ff1146d2315189fd
  Actual: 035a882ec96f190e4ec6929913bdd8880035494f9ffe27e109c828eefb35945b
    File: /Users/artvandelay/Library/Caches/Homebrew/downloads/207da8137bb7771b5ff9518936b87c46ea1f1c42866b8cb2d21c91fe8025e88e--SageMath-9.5_x86_64.dmg
To retry an incomplete download, remove the file above.
```

I have double checked the sha256 hash of SageMath-9.5_x86_64.dmg and it appears to be `035a882ec96f190e4ec6929913bdd8880035494f9ffe27e109c828eefb35945b`

but

https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/sage.rb

seems to clearly have the wrong hash. There is also a sha256 hash for non-Intel macs which I didn't check.

**Comment by culler** [comment]
Please report this at the [hombrew-cask](https://github.com/Homebrew/homebrew-cask) project.  This project has no connection with that one.

You can tell them that the assets were updated a short time after the prerelease was converted to a release in order to fix a minor bug that appeared immediately after the conversion.  I don't anticipate any other changes to the release's assets, but we currently do not guarantee that it won't happen.  While we may revisit this policy, for now you can avoid issues like this by simply downloading our release from our site.

**Comment by culler** [comment]
FYI - I submitted a [PR](https://github.com/Homebrew/homebrew-cask/pull/118757) at Homebrew-Cask with the new hashes.
