### ISSUE TITLE
Resize icon

### ISSUE THREAD

**Issue by teunzwart** [3-manifolds/Sage_macOS#47]
Currently the icon for SageMath is somewhat larger than those of other apps (see attached screenshot).
Would it be possible to slightly resize the icon so that its size is the same?

<img width="780" alt="Screenshot 2022-11-05 at 17 04 22" src="https://user-images.githubusercontent.com/6598849/200129568-08670092-14f0-4503-898f-9e3d1a291d74.png">

**Comment by culler** [comment]
Thanks. I will look into this.  I am reluctant to do a release just to adjust the icon size, but if I figure out how to do it I will replace the icon in the next release.

**Comment by teunzwart** [comment]
Thanks. Absolutely no rush

**Comment by culler** [comment]
Unfortunately this is not as simple as it might seem.  When I made the icon I took some care to try to make it be the right size.  So I was a little surprised by your screenshot, which I assumed was a screenshot of the dock.  However, here are two screenshots of my docks, one from Big Sur and one from Monterey.  The icon appears to be the right size.  I also made careful measurements in the Finder icon view of my Applications folder, and the SageMath icon is the same size as the other icons and the space between the icon and the name is larger than in your screenshot.  So I guess I would need a lot more detail about what is the exact context where you see the SageMath icon as being larger than others.  I am not able to find a context where that happens.

![DockShot1](https://user-images.githubusercontent.com/1302847/200224184-38dd23ae-5cac-47d1-9d75-9025d5dd48dc.png) 
![DockShot2](https://user-images.githubusercontent.com/1302847/200224265-30935c08-c1a8-4f74-849a-b5db48bed1ae.png)

**Comment by culler** [comment]
I finally figured this out.  First I discovered that he icon appeared with normal size on normal monitors but it appeared slightly larger on retina screens.  The problem turned out to be a bug in the script I used to generate the .icns file.  A .icns file is generated from 10 .png images, 5 for normal screens and 5 for retina screens.  The 256x256@2x image for retina screens should be 512x512.  My script was making it 256x256.  Once I corrected that the icon was the correct size on both normal and retina screens.  This will be fixed in the 10.3 release which will happen soon.  So I am closing this ticket.
